members/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

outings/urls.py
from django.urls import path

from . import views
from . import ajax

app_name = 'skiclubtouring'
urlpatterns = [
    path('', views.index, name='index'),
    path('outings', views.outings),
    path('outing/new', views.outing_new, name='outing_new'),
    path('outing/<int:oid>', views.details, name='outing'),
    path('outing/<int:oid>/subscribe',views.subscribe, name='subscribe'),
    path('outing/<int:oid>/list', views.members, name='outing_list'),
    path('outing/<int:oid>/toggle', views.outing_toggle, name='outing_toggle'),
    path('outing/<int:oid>/remove', views.outing_remove, name='outing_remove'),
    path('outing/<int:oid>/status', views.outing_status, name='outing_status'),
    path('details', views.details,),  # TODO remove at some point
    path('members', views.members),  # TODO remove at some point
    path('subscribe', views.subscribe),  # TODO remove at some point
    path('map', views.map),
    path('map-all', views.map_all),
    path('photos', views.photos),
    path('photospublic', views.photos_simple),
    path('member', views.member_outing, name="member"),
    path('member/instructor', views.season_summary, name="instructor"),
    path('stats', views.stats, name="stats"),
    path('export-draft', views.export),
    path('ajax/outingsof/<int:mid>', ajax.outings),
    path('ajax/stats/global', ajax.stats_global),
    path('ajax/stats/global/season/<int:sid>', ajax.stats_season),
    path('ajax/stats/user/outings', ajax.stats_outings),
    path('ajax/stats/user/regions', ajax.stats_regions)
]

skiclubtouring/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('outings.urls')),
    path('details', include('outings.urls')),
    path('admin/', admin.site.urls),
    path('options/', include('django.contrib.auth.urls')),
]

outings/forms.py
from django import forms
from django.forms import ValidationError

from .models import *

from members.models import Member
from outings.models import OutingTeam

import calendar
import datetime


class LoginForm(forms.Form):
    username = forms.CharField(max_length=25)
    username.widget.attrs = {'size': 8}
    password = forms.CharField(max_length=30, widget=forms.PasswordInput)
    password.widget.attrs = {'size': 8}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class OutingMemberForm(forms.ModelForm):
    class Meta:
        model = OutingTeam
        fields = ('status', 'contact_email', 'contact_mobile', 'comments', 'dva', 'probe', 'shovel')


class OutingForm(forms.ModelForm):
    class Meta:
        model = Outing
        fields = ('official', 'place', 'start_date',
                  'max_participants', 'details', 'note')

outings/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.db.models import Q
from django.db.models import Count, Sum
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.contrib.messages import get_messages
from django.contrib import messages

from django.views.decorators.clickjacking import xframe_options_exempt

from django.template import loader
from django.template.defaulttags import register
from django.views.decorators.csrf import csrf_protect

from outings.forms import *
from members.models import *
from places.models import *

from skiclubtouring.settings import MAIN_PAGE_HOME_BUTTON, PUBLIC_EMAIL, WEB_APP_AUTHOR

import datetime


class OneDetails:
    # TODO maybe move it to some external utility classes
    def __init__(self, totalOutings=0, currentSeasonOutings=0, cancelledMemberOutings=0, secuDay=False):
        self.totalOutings = totalOutings
        self.currentSeasonOutings = currentSeasonOutings
        self.cancelledMemberOutings = cancelledMemberOutings
        self.secuDay = secuDay
        self.badge = 'danger'
        if totalOutings > 10:
            self.badge = 'warning'
        if totalOutings > 30:
            self.badge = 'success'


def getLoggedMember(request):
    logged_user_first_name = 'Stranger, try to login'
    logged_user = False
    if request.user.is_authenticated:
        logged_user_first_name = request.user.first_name
        logged_user = True
    return logged_user, logged_user_first_name


def establish_variables(request):
    # TODO fix this function as I have no idea what I wanted to achieve///
    req_season = request.GET.get("season")
    err = None
    season = None
    try:
        season_year = int(req_season)
        season = Season.objects.filter(end=season_year).first()
    except (ValueError, TypeError):
        pass
    if season is None:
        season = Season.objects.order_by("-end").first()
        if season is None:
            return None, ["No seasons found."]
        if req_season:
            err = "No season like '{}' found. Switching to the last one in the calendar: {}".format(
                req_season, season
            )
    return (
        season,
        [err],
    )


def find_future_active_WE():
    saturday, sunday = find_future_active_WE_full()
    return [saturday.strftime("%Y-%m-%d"), sunday.strftime("%Y-%m-%d"), int(saturday.strftime("%Y"))]


def find_future_active_WE_full():
    SATURDAY = 5
    SUNDAY = 6
    today = datetime.date.today()
    if today.weekday() in [SATURDAY, SUNDAY]:
        if today.weekday() == SATURDAY:
            return today, today + datetime.timedelta(1)
        else:
            return today - datetime.timedelta(1), today
    else:
        saturday = today + datetime.timedelta((SATURDAY - today.weekday()) % 7)
        sunday = today + datetime.timedelta((SUNDAY - today.weekday()) % 7)
        return saturday, sunday


def static_context_and_add(request, toAdd={}):
    toReturn = {'activeWE': find_future_active_WE(),
                'messages': get_messages(request),
                'webPageHome': MAIN_PAGE_HOME_BUTTON,
                'publicContactEmail': PUBLIC_EMAIL,
                'webAppAuthor': WEB_APP_AUTHOR,
                'smallListView': False,
                }
    for key, item in toAdd.items():
        toReturn[key] = item
    return toReturn


def login_view(request, context={}):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = authenticate(
                username=login_form.cleaned_data['username'].lower(),
                password=login_form.cleaned_data['password']
            )
            if user is not None:
                login(request, user)
            else:
                messages.error(request, 'Username/password incorrect')
            return redirect('/')
        else:
            messages.error(request, 'The form you submitted could not be validated, please try again')
    else:
        login_form = LoginForm({})
    context['login_form'] = login_form
    return render(request=request,
                  template_name='login.html',
                  context=context)


def logout_view(request):
    logout(request)
    return render(request=request,
                  template_name='outings.html')


def prepareErrorPage(request, alert):
    context = {'errorMessage': alert, }
    return render(request, 'error.html', context)


def generate_main_context_for_outings_list(request):
    active_season, alertMessages = establish_variables(request)
    web_messages = WebMessage.objects.filter(valid=True)
    for one in web_messages:
        alertMessages.append(one.description)
    logged_user, logged_user_first_name = getLoggedMember(request)

    seasons = Season.objects.all().order_by('-end')
    scheduled_outings = Outing.objects.filter(season=active_season).filter(~Q(status__name='DRAFT')).order_by(
        'start_date', 'created')
    scheduled_outings_length = len(Outing.objects.filter(season=active_season).filter(status__name='OK').order_by(
        'start_date', 'created'))
    instructor_logged = False
    if logged_user and request.user.instructor:
        scheduled_outings = Outing.objects.filter(season=active_season).order_by('start_date', 'created')
        instructor_logged = True
    scheduled_outings_all = {}
    scheduled_outings_subscribe = {}
    for one in scheduled_outings:
        outing_instructors = OutingTeam.objects.filter(outing=one, member__instructor=True)
        scheduled_outings_all[one] = outing_instructors
        if one.open_sub:
            scheduled_outings_subscribe[one] = outing_instructors
    context = static_context_and_add(request, toAdd={'scheduled_outings': scheduled_outings,
                                                     'scheduled_outings_all': scheduled_outings_all,
                                                     'scheduled_outings_length': scheduled_outings_length,
                                                     'scheduled_outings_subscribe': scheduled_outings_subscribe,
                                                     'seasons': seasons,
                                                     'logged_user_first_name': logged_user_first_name,
                                                     'logged_user': logged_user,
                                                     'alertMessages': alertMessages,
                                                     'active_season': active_season,
                                                     'innerClub': False,
                                                     'instructor_logged': instructor_logged})
    return context


def index(request):
    context = generate_main_context_for_outings_list(request)
    return render(request, 'outings.html', context)


@xframe_options_exempt
def outings(request):
    context = generate_main_context_for_outings_list(request)
    context['smallListView'] = True  # override the one from the basic context
    return render(request, 'outings-simple.html', context)


def generate_main_context_for_photos_list(request):
    active_season, alertMessages = establish_variables(request)
    logged_user, logged_user_first_name = getLoggedMember(request)

    seasons = Season.objects.all().order_by('-end')
    scheduled_outings = Outing.objects.filter(season=active_season).order_by('-start_date')
    scheduled_outings_all = {}
    for one in scheduled_outings:
        outing_instructors = OutingTeam.objects.filter(outing=one, member__instructor=True)
        outing_photos = OutingTeam.objects.filter(outing=one).filter(~Q(url_photo=None))

        if len(outing_photos):
            scheduled_outings_all[one] = (outing_instructors, outing_photos)

    context = static_context_and_add(request, toAdd={'logged_user_first_name': logged_user_first_name,
                                                     'logged_user': logged_user,
                                                     'scheduled_outings_all': scheduled_outings_all,
                                                     'seasons': seasons,
                                                     'alertMessages': alertMessages,
                                                     'active_season': active_season,
                                                     'innerClub': False,
                                                     })
    return context


def photos(request):
    context = generate_main_context_for_photos_list(request)
    return render(request, 'photos.html', context)


@xframe_options_exempt
def photos_simple(request):
    context = generate_main_context_for_photos_list(request)
    context['smallListView'] = True  # override the one from the basic context
    return render(request, 'photos-simple.html', context)


def map(request):
    active_season, alertMessages = establish_variables(request)
    seasons = Season.objects.all().order_by('-end')
    scheduled_outings = Outing.objects.filter(season=active_season, status__name='OK').order_by('start_date')
    context = static_context_and_add(request, toAdd={'scheduled_outings': scheduled_outings,
                                                     'seasons': seasons,
                                                     'alertMessages': alertMessages,
                                                     'innerClub': False,
                                                     'active_season': active_season,
                                                     })
    return render(request, 'map-new.html', context)


def map_all(request):
    places_outings = {}
    for place in Place.objects.all():
        outings = Outing.objects.filter(place=place, status__name='OK').order_by('-start_date')

outings/templates/button-outing.html
{% load static %}
<a class="btn btn{% if not outing.is_past_due %}-outline-secondary{%else%}-secondary{%endif%} {%if smallListView%}btn-sm{%endif%}" {%if smallListView%}target="new"{%endif%} href="{% url 'skiclubtouring:outing' outing.outing_id %}">
  {% if more_details %}  <span class="badge badge-info">{{outing.day_of_week}} {{outing.start_date}}</span> {%endif%}
  {% if 'DRAFT' in outing.status.name %}<span class="badge badge-primary">DRAFT<img src="{% static 'img/draft.png' %}" width="16" height="16"/></span>{% endif%}
  {% if 'CANCELED' in outing.status.name %}<span class="badge badge-warning">CANCELED<img src="{% static 'img/accident.png' %}" width="16" height="16"/></span>{% endif%}
  <strong>{{outing.place.name}}</strong> <small>({{outing.place.massif}})</small> <span class="badge badge-dark">{{outing.place.total_ski_grade}}</span>
  {% if not outing.official %}<span class="badge badge-danger">NON-OFFICIAL<img src="{% static 'img/lock.png' %}" width="16" height="16"/></span>{% endif%}
  {% if outing.max_participants %}<span class="badge badge-warning">MAX:<img src="{% static 'img/skier.png' %}" width="16" height="16"/> {{outing.max_participants}}</span>{% endif%}
  {% if outing.gps_file_name %}<span class="badge badge-primary">GPX<img src="{% static 'img/gps.png' %}" width="16" height="16"/> </span>{% endif%}
</a>

outings/templates/map-new.html
{% extends 'map.html' %}
{% block 'features' %}

    {%for outing in scheduled_outings %}
    {% if outing.place.long != None  %}
    new ol.Feature({
        geometry : new ol.geom.Point(ol.proj.fromLonLat([{{outing.place.long}},{{outing.place.lat}}])),
        desc  : '<div class="card" style="width: 24rem;"><div class="card-body">\
                <a class="link" href="{% url 'skiclubtouring:outing' outing.outing_id %}">{% autoescape on %}{{outing.place.name_simple}} ({{outing.place.alt_summit}}m){% endautoescape %}</a><br>\
                    {{outing.place.total_ski_grade}}<br>{{outing.start_date}}<br><br>STATUS: {{outing.status}} </div></div>\ ',
          }),
    {% endif%}
    {% endfor %}

{% endblock %}

outings/templates/nav_main.html
{% extends 'nav_template.html'%}
{% block 'options' %}

    <div class="collapse navbar-collapse" id="navbars1">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Past seasons</a>
          <div class="dropdown-menu" aria-labelledby="dropdown2">
            {%for season in seasons %} <a class="dropdown-item" href="/?season={{season.end}}">{{season}}  {% if 'Manual' in season.description %}
              <span class="badge badge-warning">sparse</span> {%endif%} </a> {% endfor %}
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="map-all">Show all Club's destinations ever {% load static %}<img src="{% static 'img/map.png' %}" width="24" height="24"/></a>
        </li>
        <li class="nav-item">
          <a class="btn btn-outline-success" href={% url 'skiclubtouring:member'%}>Hello {{logged_user_first_name}}!</a>
        </li>
        {% if instructor_logged %}
        <li class="nav-item active">
          <a class="btn btn-outline-danger" href="/admin">ADMIN PANELs</a>
        </li>
        {% endif %}
      </ul>
    </div>

  {% endblock %}

outings/templates/nav_simple.html
{% extends 'nav_template.html'%}
{% block 'options' %}
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/?season={{season.end}}">Back to the {{season}} season </a>
      </li>
    </ul>
  </div>
{% endblock %}

outings/templates/outings-simple.html
{% extends 'main_template.html' %}
{% block 'body' %}
<main role="main">
  <div class="col-sm-8 mx-auto">
  {% if scheduled_outings_all.items|length == 0 %}
  <div class="col-sm-8 mx-auto">
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    No outings are scheduled/recorded for this season.
  </div>
  </div>
  {% else %}
  {% include 'alert-box.html' with messages=messages level='warning'%}
  {% include 'alert-box.html' with alertMessages=messages level='success'%}
<!--      {% include 'alert-ffsrules.html' %}-->
<!--      {% include 'alert-covid.html' %}-->

  <table class="table table-hover">
   <thead>
     <tr class="table" >
       <th scope="col">{% load static %}<img src="{% static 'img/calendar.png' %}" width="16" height="16" /> When</th>
       <th scope="col">{% load static %}<img src="{% static 'img/gps.png' %}" width="16" height="16" /> Where</th>
     </tr>
   </thead>
   <tbody>
     {% for outing, instructors in scheduled_outings_all.items %}
     <tr {% if outing.is_past_due %} class='table-secondary'
         {% elif 'CANCELED' in outing.status.name %} class='table-warning'
         {% elif outing.start_date|date:"Y-m-d" in activeWE %} class='table-info' id='activeWE'
     {% endif%}>
       <td>{%if smallListView%}<small>{%endif%}<span class="badge badge-info"> {{outing.day_of_week}} {{outing.start_date}}</span> {% for inst in instructors %}
         <span class="badge badge-light">{{inst.member.first_name}}</span> {%endfor%} {%if smallListView%}</small>{%endif%} </td>
       <td>
         {% include 'button-outing.html' with outing=outing %}
         {% if outing.open_sub  %}<a class="btn btn-success {%if smallListView%}btn-sm{%endif%}" href="{% url 'skiclubtouring:subscribe' outing.outing_id %}" target="new"> Subscribe!</a>{% endif%}
         {% if outing.details != None and outing.details|length != 0 %}<div><em>{{outing.details}}</em></div>{% endif%}
         {% if outing.note != None and outing.note|length != 0  %}<div class="alert alert-danger"><p>{{outing.note}}</p></div>{% endif%}
        </td>
     </tr>
     {% endfor %}
   </tbody>
 </table>
</div>
{% endif %}
</main>
{% endblock %}

outings/templates/outings.html
{% extends 'main_template.html' %}
{% block 'navigation' %}
{% include 'nav_main.html' %}
{% endblock %}
{% block 'body' %}
<main role="main">
  <div class="jumbotron">
    <div class="col-sm-8 mx-auto">
      <h1>Season {{active_season}} outings  <a class="btn btn-outline-info" href="?season={{activeWE.2}}#activeWE" role="button">
        Jump to the next active week-end <span class="badge badge-info">{{activeWE.0}}</span> - <span class="badge badge-info">{{activeWE.1}}</span></a></h1>
      {% include 'alert-box.html' with messages=messages level='warning'%}
      {% include 'alert-box.html' with alertMessages=messages level='success'%}

<!--      {% include 'alert-ffsrules.html' %}-->
<!--      {% include 'alert-covid.html' %}-->

      <p>Note that this is a preliminary schedule and
        <strong>we have tentatively scheduled/completed: {{scheduled_outings_length}} outings</strong>.<br>
        This number may, and most certainly will(!), evolve during the season, as more detailed weather forecasts
        and instructors' availability evolves.
      </p>
        {% if 'Manual' in active_season.description %}
        <div class="alert alert-warning"> This season is marked as <span class="badge badge-warning">SPARSE</span>, it contains only a selected history of the outings that are step by step updated by our instructors browsing old outings logs in the search of new ideas and inspirations. Enjoy the time travel while reading about those outings. </div>
        {% endif%}

      <p>
        Check  <a class="btn btn-outline-secondary" href="/map?season={{active_season.end}}" role="button">all the {{active_season}} season's outings on the map{% load static %}<img src="{% static 'img/map.png' %}" width="32" height="32"/></a>
        or browse  <a class="btn btn-outline-secondary" href="/photos?season={{active_season.end}}" role="button">all pictures taken during the outings {% load static %}<img src="{% static 'img/camera.png ' %}" width="32" height="32"/></a>
      </p>

      <hr>
      <p>This is public view for the club's members and guests. We are part of the <a class="badge badge-light" target="new" href="http://www.kananas.com/skiclubcern/">CERN SkiClub.</a><br>
        All the details of how to subscribe, how we organize outings and about the team behind our section you can find on
        <a class="badge badge-light" target="new" href="http://www.kananas.com/skiclubcern/activites/ski-de-randonnee/">  our CERN SkiClub Ski Touring Section information page.</a>
      </p>
      <hr>
      <p>Last but not least, remember to tag your photos with <a class="badge badge-secondary" target="new" href="https://www.instagram.com/explore/tags/cernskitouring/">#cernskitouring</a>
        when you post them on your favorites social medias.</p>
    </div>
    <div class="col-sm-6 mx-auto">
      <hr>
    <table class="table alert-success">
    {% for outing, instructors in scheduled_outings_subscribe.items %}
     <tr class="bg-gradient-success">
     <td><span class="badge badge-info"> {{outing.day_of_week}} {{outing.start_date}}</span> {% for inst in instructors %}
         <span class="badge badge-light">{{inst.member.first_name}}</span> {%endfor%} </td>
        <td>
         {% include 'button-outing.html' with outing=outing %}
         <a class="btn btn-success" href="{% url 'skiclubtouring:subscribe' outing.outing_id %}"> Subscribe!</a>
        </td>
     </tr>
     {% endfor %}
        </table>
    </div>
  </div>
  {% if scheduled_outings_all.items|length == 0 %}
  <div class="col-sm-8 mx-auto">
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    No outings are scheduled/recorded for this season.
  </div>
  </div>
  {% else %}
  <div class="col-sm-8 mx-auto">
  <table class="table table-hover">
   <thead>
     <tr class="table" >
       <th scope="col">{% load static %}<img src="{% static 'img/calendar.png' %}" width="16" height="16" /> When</th>
       <th scope="col">{% load static %}<img src="{% static 'img/gps.png' %}" width="16" height="16" /> Where</th>
     </tr>
   </thead>
   <tbody>
     {% for outing, instructors in scheduled_outings_all.items %}
     <tr {% if outing.is_past_due %} class='table-secondary'
         {% elif 'CANCELED' in outing.status.name %} class='table-warning'
         {% elif outing.start_date|date:"Y-m-d" in activeWE %} class='table-info' id='activeWE'
     {% endif%}>
     <td><span class="badge badge-info"> {{outing.day_of_week}} {{outing.start_date}}</span> {% for inst in instructors %}
         <span class="badge badge-light">{{inst.member.first_name}}</span> {%endfor%} </td>
       <td>
         {% include 'button-outing.html' with outing=outing %}
         {% if outing.open_sub  %}<a class="btn btn-success" href="{% url 'skiclubtouring:subscribe' outing.outing_id %}"> Subscribe!</a>{% endif%}
         {% if outing.details != None and outing.details|length != 0 %}<div><em>{{outing.details}}</em></div>{% endif%}
         {% if outing.note != None and outing.note|length != 0  %}<div class="alert alert-{% if not outing.is_past_due %}danger{%else%}secondary{%endif%}"><p>{{outing.note}}</p></div>{% endif%}
        </td>
     </tr>
     {% endfor %}
   </tbody>
 </table>
</div>
  {% endif %}
</main>
{% endblock %}

outings/templates/season_summary.html
{% extends 'main_template.html' %}
{% block 'navigation' %}
{% include 'nav_member.html' %}
{% endblock %}
{% block 'body' %}
    <main role="main">
      <div class="jumbotron">
        <div class="col-sm-8 mx-auto">
          <h1>Hello {{member.first_name}}!</h1>
          This is an isnstructor view.
          {% include 'alert-box.html' with level='warning'%}
          <br>
          <a class="btn btn-primary" href={% url 'skiclubtouring:outing_new'%}> <strong>Add new DRAFT Outing</strong></a>
          <a class="btn btn-outline-primary" href="#nextweekend">Upcoming weekend outings</a>
                    <a class="btn btn-outline-primary" href="#activemembers">{{season}} active members statistics</a>
          <a class="btn btn-outline-primary" href="#instrutorsseasonend">The instructors' season summary</a>
        <hr>
          <h4>Your current draft outings</h4>
          {%for one in draftOutings%} <p>{% include 'button-outing.html' with outing=one more_details=1 %}
             <a class="btn btn-outline-primary" href="{% url 'skiclubtouring:outing_status' one.outing_id%}">Finalise Draft -> OK</a>
             <a class="btn btn-outline-danger" href="{% url 'skiclubtouring:outing_remove' one.outing_id %}">Remove</a>
            </p> {%endfor%}
            <h4> All season's opened subscriptions</h4>
           {% for one in open_subscriptions_outings%}
              <p>{% include 'button-outing.html' with outing=one more_details=1%}
                  <a class="btn btn-outline-primary" href="{% url 'skiclubtouring:outing_toggle' one.outing_id%}">Close subscriptions</a></p>
           {% endfor%}

        </div>

      </div>

      <div class="col-sm-8 mx-auto">
      <a id="nextweekend"/>
    <h2> All upcoming (current) weekend highlights</h2>

      {% for outing in next_weekend_outing%}
      <div class="alert alert-secondary">
        <h4>{% include 'button-outing.html' with outing=outing more_details=1 %}
          {%if outing.open_sub%}<span class="badge badge-success">Subscriptions Opened</span>{%endif%}</h4>
        <h5>Participant(s) <span class="badge badge-dark">{{next_weekend_details|get_item:outing.outing_id|length}}</span>, <small>including confirmed and on waiting list </small>:</h5>
        {% if instructor_logged %}
        <a class="btn btn-outline-primary" href="{% url 'skiclubtouring:outing_list' outing.outing_id %}" target="new">See detailed participants details </a> <br>
        <a class="btn btn-outline-primary" href="{% url 'skiclubtouring:outing_toggle' outing.outing_id %}" target="new">{%if outing.open_sub%}CLOSE{%else%}OPEN{%endif%} Subscriptions</a>

        <form class="post-form" action="{% url 'skiclubtouring:outing_status' outing.outing_id%}" method="POST">
            {% csrf_token %}
            <select class="btn btn-outline-primary dropdown-toggle"
                    onchange='document.getElementById("submit{{outing.outing_id}}").disabled=false;'
                    name="status" >
            {%for one in statuses%}<option value="{{one}}" {%if one == outing.status%}selected{%endif%}>{{one}}</option>{%endfor%}
            </select>
          <input id="submit{{outing.outing_id}}" class="btn btn-outline-primary" type="submit" value="Update Status" disabled>
        </form>

      {% endif %}
        <hr>
      {% for participant in next_weekend_details|get_item:outing.outing_id%}
        {{ forloop.counter }} {% include 'outing-member.html' with outingMember=participant.0 outingMemberStat=participant.1 %} <br>
      {% endfor%}
      </div>
       {% endfor%}

          <a id="activemembers"/>
        <h2> {{season}} active members statistics</h2>
          <p>This season participation in Security days EXCLUDED!</p>
          <hr>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Member</th>
                <th scope="col">MF</th>
                <th scope="col">{{season}} #</th>
                <th scope="col">All time #</th>
              </tr>
            </thead>
            <tbody>
            {%for member in active_members%}
            {%if active_members_outings|get_item:member.member_id != None%}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{member.name}}</td>
                  <td>{{member.instructor}}</td>
                  <td>{{active_members_outings|get_item:member.member_id}}</td>
                  <td>{{active_members_outings_all|get_item:member.member_id}}</td>
                </tr>{%endif%}{% endfor %}
            </tbody>
          </table>


        <a id="instrutorsseasonend"/>
        <h2> This is instructor's view for the {{season}} season summary</h2>
          <p>This list can be used to prepare a budget report for the SkiClubCommittee </p>
          <hr>
          {% for ins in instructors %}
          <h5>{{ins}} <span class="badge badge-secondary">Total: {{instructors_outing|get_item:ins.member_id|length}}</span></h5>
          {%if instructors_outing|get_item:ins.member_id|length%}
           <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">Outing</th>
                <th scope="col">Link</th>
              </tr>
            </thead>
            <tbody>
            {%for outing in instructors_outing|get_item:ins.member_id%}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{outing.start_date}}</td>
                  <td>{{outing}}</td>
                  <td> <a class="btn btm-sm btn-outline-secondary" href="{% url 'skiclubtouring:outing' outing.outing_id %}"><b>>></b></a></td>
                </tr>{% endfor %}
            </tbody>
          </table>
         {%endif%}
          {% endfor %}

      </div>

    </main>
{% endblock %}